spring.application.name=WayMail
spring.data.mongodb.uri=mongodb+srv://bernardo16barreto:4gKDDHwLb9lWLqMS@lothuspay.bgtwm2b.mongodb.net/wayemails?retryWrites=true&w=majority&appName=WayMail
resend.api.key=re_HkyT1b55_Jbu6CViN3r6UotYK16PTstb8

# Logging Configuration
logging.file.name=logs/waymail.log
logging.level.root=INFO
logging.level.com.bremado=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
